In [1]:
import torch

In [2]:
xs = torch.tensor([0,1,2,3,4,5,6,7.])

In [10]:
ys = torch.tensor([1.86,1.31,0.62,0.09,-0.67,-1.23,-1.37, -1.45])

slope of line is given by $y = mx +b$

In [4]:
def regression(my_x, my_m, my_b):
    return my_m*my_x + my_b

Initalize with $m$ and $b$ with some 'random' near zero-value

In [5]:
m = torch.tensor([0.9]).requires_grad_()

In [12]:
b = torch.tensor([0.1]).requires_grad_()

to keep partial derivatives as simple, let move forward with single instance

In [11]:
i = 7
x = xs[i]
y = ys[i]

In [13]:
x

tensor(7.)

In [14]:
y

tensor(-1.4500)

**Step-1** : Forward Pass

In [27]:
yhat = regression(x, m, b)
yhat

tensor([6.4000], grad_fn=<AddBackward0>)

**Step-2** : Compare $\hat{y}$ with true $y$ to calc. cost c


In [28]:
def squared_error(my_yhat, my_y):
    print(f"y:{my_yhat - my_y}")
    return (my_yhat - my_y) ** 2

In [29]:
C = squared_error(yhat, y)
C

y:tensor([7.8500], grad_fn=<SubBackward0>)


tensor([61.6225], grad_fn=<PowBackward0>)

**STEP-3** : USe autodiff to calculate gradient of C wrt parameters

In [30]:
C.backward()

In [31]:
m.grad

tensor([109.9000])

In [32]:
b.grad

tensor([15.7000])

$\frac{\delta C}{\delta m} = 2x(\hat{y} - y)$

In [33]:
2*x*(yhat.item()-y)

tensor(109.9000)

$\frac{\delta C}{\delta m} = 2(\hat{y} - y)$

In [36]:
2*(yhat.item()-y)

tensor(15.7000)

In [37]:
gradient = torch.tensor([[b.grad.item(), m.grad.item()]]).T
gradient

tensor([[ 15.7000],
        [109.9000]])